import { toast } from 'react-hot-toast';

export const programs = [
  {
    id: 1,
    program: 'Program A',
    category: 'Category 1',
    package: 'Package X',
    imageURL: 'xxxx1',
    desc: 'Lorem ipsum dolor sit amet',
    isSubscribe: true,
  },
  {
    id: 2,
    program: 'Program B',
    category: 'Category 2',
    package: 'Package Y',
    imageURL: 'xxxx2',
    desc: 'Lorem ipsum dolor sit amet',
    isSubscribe: false,
  },
  {
    id: 3,
    program: 'Program C',
    category: 'Category 1',
    package: 'Package Z',
    imageURL: 'xxxx3',
    desc: 'Lorem ipsum dolor sit amet',
    isSubscribe: true,
  },
  {
    id: 4,
    program: 'Program D',
    category: 'Category 3',
    package: 'Package X',
    imageURL: 'xxxx4',
    desc: 'Lorem ipsum dolor sit amet',
    isSubscribe: false,
  },
  {
    id: 5,
    program: 'Program E',
    category: 'Category 2',
    package: 'Package Y',
    imageURL: 'xxxx5',
    desc: 'Lorem ipsum dolor sit amet',
    isSubscribe: true,
  },
  {
    id: 6,
    program: 'Program F',
    category: 'Category 3',
    package: 'Package Z',
    imageURL: 'xxxx6',
    desc: 'Lorem ipsum dolor sit amet',
    isSubscribe: false,
  },
  {
    id: 7,
    program: 'Program G',
    category: 'Category 1',
    package: 'Package X',
    imageURL: 'xxxx7',
    desc: 'Lorem ipsum dolor sit amet',
    isSubscribe: true,
  },
  {
    id: 8,
    program: 'Program H',
    category: 'Category 2',
    package: 'Package Y',
    imageURL: 'xxxx8',
    desc: 'Lorem ipsum dolor sit amet',
    isSubscribe: false,
  },
  {
    id: 9,
    program: 'Program I',
    category: 'Category 3',
    package: 'Package Z',
    imageURL: 'xxxx9',
    desc: 'Lorem ipsum dolor sit amet',
    isSubscribe: true,
  },
  {
    id: 10,
    program: 'Program J',
    category: 'Category 1',
    package: 'Package X',
    imageURL: 'xxxx10',
    desc: 'Lorem ipsum dolor sit amet',
    isSubscribe: false,
  },
];

export const myToaster = (message) =>
  toast(message, {
    duration: 3000,
    position: 'bottom-center',
    style: {
      background: '#6750A4',
      color: 'white',
    },
  });
